package com.portfolio.taskmanager.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Entity class representing a Task in the database.
 *
 * KEY CONCEPTS:
 * - @Entity: Tells JPA that this class maps to a database table.
 * - @Table: Specifies the table name (defaults to class name if omitted).
 * - @Id + @GeneratedValue: Creates an auto-incrementing primary key.
 * - @Enumerated(EnumType.STRING): Stores enum values as readable strings (e.g., "HIGH")
 *   instead of numbers (e.g., 0, 1, 2), which makes the database easier to read.
 *
 * Lombok annotations (@Data, @NoArgsConstructor, etc.) auto-generate boilerplate code
 * like getters, setters, constructors, toString(), equals(), and hashCode().
 */
@Entity
@Table(name = "tasks")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Task {

    /**
     * Unique identifier for each task.
     * Auto-generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the task (required field).
     * Cannot be null in the database.
     */
    @Column(nullable = false)
    private String title;

    /**
     * Detailed description of the task (optional).
     * Using @Column(length = 500) to allow longer text.
     */
    @Column(length = 500)
    private String description;

    /**
     * Current status of the task.
     * Defaults to PENDING when a new task is created.
     * Stored as a readable string in the database (e.g., "PENDING", "COMPLETED").
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TaskStatus status = TaskStatus.PENDING;

    /**
     * Priority level of the task.
     * Defaults to MEDIUM if not specified.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Priority priority = Priority.MEDIUM;

    /**
     * Timestamp when the task was first created.
     * Automatically set by Hibernate — no need to set it manually.
     */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the last update to the task.
     * Automatically updated by Hibernate on every save.
     */
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
